In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
cust = pd.read_csv('cleaned_customer_data.csv')
total = pd.read_csv('transaction_data.csv')

In [16]:
cust_total = pd.merge(cust, total, left_on='Cust_id', right_on='CustID', how='inner')
cust_total.head(10)

,Cust_id,Date_x,Time,Name,Email,Phone,Sms-opt-out,Sms_opt_out,TransactionID,CustID,...,Employee,ProductID,ProductName,VendorID,ProductVendor,UnitPrice,Quantity,Subtotal,Tax(8%),OrderTotal
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10258,1,...,Nancy Davolio,32,Mascarpone Fabioli,14,Formaggi Fortini s.r.l.,25.60,6,153.60,12.29,165.89
1,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10351,1,...,Nancy Davolio,38,Cte de Blaye,18,Aux joyeux ecclsiastiques,210.80,20,4216.00,337.28,4553.28
2,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10351,1,...,Nancy Davolio,41,Jack's New England Clam Chowder,19,New England Seafood Cannery,7.70,13,100.10,8.01,108.11
3,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10351,1,...,Nancy Davolio,65,Louisiana Fiery Hot Pepper Sauce,2,New Orleans Cajun Delights,16.80,10,168.00,13.44,181.44
4,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10773,1,...,Nancy Davolio,75,Rhnbru Klosterbier,12,Plutzer Lebensmittelgromrkte AG,7.75,7,54.25,4.34,58.59
5,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10776,1,...,Nancy Davolio,31,Gorgonzola Telino,14,Formaggi Fortini s.r.l.,12.50,16,200.00,16.00,216.00
6,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10776,1,...,Nancy Davolio,42,Singaporean Hokkien Fried Mee,20,Leka Trading,14.00,12,168.00,13.44,181.44
7,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10968,1,...,Nancy Davolio,64,Wimmers gute Semmelkndel,12,Plutzer Lebensmittelgromrkte AG,33.25,4,133.00,10.64,143.64
8,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10368,1,...,Andrew Fuller,21,Sir Rodney's Scones,8,"Specialty Biscuits, Ltd.",8.00,5,40.00,3.20,43.20
9,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,False,10368,1,...,Andrew Fuller,28,Rssle Sauerkraut,12,Plutzer Lebensmittelgromrkte AG,36.40,13,473.20,37.86,511.06

In [23]:
customer_summary = cust_total[['CustID', 'ProductName', 'Employee']]
customer_summary

      CustID                       ProductName         Employee
0          1                Mascarpone Fabioli    Nancy Davolio
1          1                      Cte de Blaye    Nancy Davolio
2          1   Jack's New England Clam Chowder    Nancy Davolio
3          1  Louisiana Fiery Hot Pepper Sauce    Nancy Davolio
4          1                Rhnbru Klosterbier    Nancy Davolio
...      ...                               ...              ...
1348      89               Sir Rodney's Scones  Steven Buchanan
1349      89                  Chartreuse verte  Steven Buchanan
1350      89      Chef Anton's Cajun Seasoning      Robert King
1351      89            Thringer Rostbratwurst   Laura Callahan
1352      89     Singaporean Hokkien Fried Mee   Laura Callahan

[1353 rows x 3 columns]